### ISSUE TITLE
Not Working in android

### ISSUE THREAD

**Issue by tmirun** [binaryminds/react-native-sse#3] opened 2021-06-21 16:44 UTC
in iOS work fine but in android it's not working
I use android 10 with react native version 0.64.0

**Comment by wojciechkrol** [comment] 2021-06-22 07:47
Hello @tmirun,

We have project in React Native 0.64.2 and we haven't noticed any issues on Android 10. Please, show us your code. Without more details we can't help you.

**Comment by tmirun** [comment] 2021-06-22 09:47
I simply copied the code in the readme, using my SSE URL with basic auth

```
const url = new URL('xxxxxxxxxxxx');

    const es = new EventSource(url, {
      headers: {
        Authorization: "Basic xxxxxxxx";
      },
    });

    const listener: EventSourceListener = (event) => {
      if (event.type === "open") {
        console.log("Open SSE connection.");
      } else if (event.type === "message") {
        console.log(`Received book ${event.data}`);
      } else if (event.type === "error") {
        console.error("Connection error:", event.message);
      } else if (event.type === "exception") {
        console.error("Error:", event.message, event.error);
      }
    };

    es.addEventListener("open", listener);
    es.addEventListener("message", listener);
    es.addEventListener("error", listener);

    return () => {
      es.removeAllEventListeners();
      es.close();
    };
  }, []);
```

**Comment by tmirun** [comment] 2021-06-22 09:49
I have discoverd where is the bug:
https://github.com/facebook/flipper/issues/2495

**Comment by wojciechkrol** [comment] 2021-06-22 11:01
Thank you for finding the cause of the problem. We will follow your issue. Please let me know: Do you use `URL` with `react-native-url-polyfill`?

From our README:
```
import "react-native-url-polyfill/auto"; // Use URL polyfill in React Native
```

**Comment by tmirun** [comment] 2021-06-23 10:07
yes, i used "react-native-url-polyfill/auto"
in the iOS work perfectlly

**Comment by forster007** [comment] 2021-07-19 20:54
Still not working on Android. Any news about it?

**Comment by Lenny4** [comment] 2021-09-18 14:50
@forster007 
https://stackoverflow.com/questions/69235694/react-native-cant-connect-to-sse-in-android/69235695

**Comment by wojciechkrol** [comment] 2022-02-14 08:38
Since this issue is connected with Flipper (in debug mode) and no possible fix on our side I'm closing this issue.

Just disable debugger/debug mode, or follow instructions above to disable Flipper network plugin.

**Closed by wojciechkrol** 2022-02-14 08:38 UTC
